version: '3.9'

services:
  web-server:
    image: nginx:latest
    container_name: web-server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    command: sh -c "echo Frontend service started && tail -f /dev/null"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "9000:9000"
    command: sh -c "echo Backend service started && tail -f /dev/null"