export enum MutationTypes {
    SET_ZONE = "SET_ZONE",
    SET_CHILDREN = "SET_CHILDREN",
    SET_PARENT = "SET_PARENT",
    PUSH_ITEM_TO_CHILDREN = "PUSH_ITEM_TO_CHILDREN",
    SET_ITEM_TO_CHILDREN = "SET_ITEM_TO_CHILDREN",
    DELETE_ZONE = "DELETE_ZONE",
    DELETE_CHILD = "DELETE_CHILD",
}
